### ISSUE TITLE
Simulator Crashes when running with Earthquake

### ISSUE THREAD

**Issue by caranha** [caranha/Koudou#9]
- @JasonJiangs reported that the simulator was crashing when running with Earthquake configuration, because the agent did not have the attribute "know_evac"
- @fhtanaka noticed that you need to change parameters/default.py to include the csv file with the evacuation attributes.

Things to do: 
- Jason should check that fabio's suggestion work
- Even if fabio's suggestion work, having to change the configuration BOTH in the csv AND in the py seems excessive and confusing. We should simplify the loading of attributes and scenarios somehow. (maybe should spin off in a new issue)

**Comment by fhtanaka** [comment]
About the second point of "Things to do":
Usually, if you want to change the changes of someone knowing the evacuation center, you just to need to change the value on the .csv.
You only need to change the .py if you want to point the simulation to another config file. What happened, is that the simulation was not pointed to any config and because of that it didnt have the attribute. 

I think this behavior, while a little troublesome, is expected because if we want to test different scenarios, we can have different config files and just change where the .py is pointing to in each test.
